// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtgye9Pq_gzD6Csad7b1adjcnDQY4OXxw',
    appId: '1:816601815157:web:47a9766eda1efbe7f0803c',
    messagingSenderId: '816601815157',
    projectId: 'aquatech01234',
    authDomain: 'aquatech01234.firebaseapp.com',
    storageBucket: 'aquatech01234.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9odwLVX8f6W3A8_zBn0hXrMrqgntb1EE',
    appId: '1:816601815157:android:e1a4f8b57a639148f0803c',
    messagingSenderId: '816601815157',
    projectId: 'aquatech01234',
    storageBucket: 'aquatech01234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Z_fIGn7nv5xCxBZ_QAu1YWi6VN1UXc0',
    appId: '1:816601815157:ios:1d9ecbf045c4f0aaf0803c',
    messagingSenderId: '816601815157',
    projectId: 'aquatech01234',
    storageBucket: 'aquatech01234.appspot.com',
    iosBundleId: 'com.example.demo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Z_fIGn7nv5xCxBZ_QAu1YWi6VN1UXc0',
    appId: '1:816601815157:ios:1633037fd2b2fc06f0803c',
    messagingSenderId: '816601815157',
    projectId: 'aquatech01234',
    storageBucket: 'aquatech01234.appspot.com',
    iosBundleId: 'com.example.demo1.RunnerTests',
  );
}
